# Generated by Django 3.0.5 on 2020-08-12 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_area_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='trackerapp.Area'),
            preserve_default=False,
        ),
    ]
